set nocompatible " Disable vi-compatibility
set t_Co=256
 
set guioptions-=T " Removes top toolbar
set guioptions-=r " Removes right hand scroll bar
set go-=L " Removes left hand scroll bar

syntax on " syntax 
syntax enable
colorscheme xoria256

set conceallevel=2

set number " always show line numbers
set tabstop=4 " a tab is 4 spaces
set showmode " always show what mode we're currently editing in
set autoindent " always set autoindenting on
set smartindent
set shiftwidth=4 " indent by 4 spaces when using >>, <<, ==
set ignorecase " ignore case when searching
set smartcase " ignore case if search pattern is all lowercase
set mouse=a " scroll with trackpad
set nowrap " don't wrap lines by default
set ttyfast "assume a fast connection to the terminal for better rendering
set history=250 "undo history
set fileformats=unix "set compatible line endings in order of preference

set backup
set backupdir=~/.vim/backup/
set directory=~/.vim/swap/

" With a map leader it's possible to do extra key combinations
" like <leader>w saves the current file
let mapleader = ","
let g:mapleader = ","

" search
map /  <Plug>(incsearch-forward)
map ?  <Plug>(incsearch-backward)
map g/ <Plug>(incsearch-stay)

" tabs
set list lcs=tab:\┆·
highlight SpecialKey ctermfg=59 guifg=#3C3C3C

" NERD Tree
nmap <C-b> :NERDTreeToggle<cr>
let NERDTreeShowHidden=1
let NERDTreeMouseMode=2
let NERDTreeKeepTreenInNewTab=1
let NERDTreeIgnore=['.DS_Store', '.git/*[[dir]]', 'node_modules', 'bower_components']

" Set Font
set guifont=Source\ Code\ Pro\ Light:h11

" Running vim-pathogen to load ~/.vim/bundle
execute pathogen#infect()
