set nocompatible " Disable vi-compatibility
set t_Co=256

set guioptions-=T " Removes top toolbar
set guioptions-=r " Removes right hand scroll bar
set go-=L " Removes left hand scroll bar

syntax on " syntax 
syntax enable

" always set background to dark
set background=dark

" if we're on gui, use base16-ocean
if has('gui_running')
    colorscheme base16-ocean
else
    colorscheme xoria256
endif

set conceallevel=2

set number " always show line numbers
set showmode " always show what mode we're currently editing in

set autoindent
set smartindent

" size of a hard tabstop
set tabstop=4

" size of an "indent"
set shiftwidth=4

" a combination of spaces and tabs are used to simulate tab stops at a width
" other than the (hard)tabstop
set softtabstop=4

" make "tab" insert indents instead of tabs at the beginning of a line
set smarttab

" always uses spaces instead of tab characters
set expandtab

set ignorecase " ignore case when searching
set smartcase " ignore case if search pattern is all lowercase
set mouse=a " scroll with trackpad
set nowrap " don't wrap lines by default
set ttyfast "assume a fast connection to the terminal for better rendering
set history=250 "undo history
set fileformats=unix "set compatible line endings in order of preference

set backup
set backupdir=~/.vim/backup/
set directory=~/.vim/swap/

" With a map leader it's possible to do extra key combinations
" like <leader>w saves the current file
let mapleader = ","
let g:mapleader = ","

" search
map /  <Plug>(incsearch-forward)
map ?  <Plug>(incsearch-backward)
map g/ <Plug>(incsearch-stay)

" tabs
set list lcs=tab:\┆·
highlight SpecialKey ctermfg=59 guifg=#65737e

" NERD Tree
nmap <C-b> :NERDTreeToggle<cr>
let NERDTreeShowHidden=1
let NERDTreeMouseMode=2
let NERDTreeKeepTreenInNewTab=1
let NERDTreeIgnore=['.DS_Store', '.git/*[[dir]]', 'node_modules', 'bower_components', 'vendor']

" Set Font
set guifont=Sauce\ Code\ Powerline\ Light:h11

" Set lightline colors
let g:lightline = {
      \ 'colorscheme': 'wombat',
      \ 'component': {
      \   'readonly': '%{&readonly?"":""}',
      \ },
      \ 'separator': { 'left': '', 'right': '' },
      \ 'subseparator': { 'left': '', 'right': '' }
      \ }

" Running vim-pathogen to load ~/.vim/bundle
execute pathogen#infect()
